# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='document_search.proto',
  package='document_search',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x64ocument_search.proto\x12\x0f\x64ocument_search\"&\n\x13SearchContentResult\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x0fSearchNumResult\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"*\n\x0bSearchQuery\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2\xc1\x01\n\x15\x44ocumentSearchService\x12V\n\x0eSearchContents\x12\x1c.document_search.SearchQuery\x1a$.document_search.SearchContentResult\"\x00\x12P\n\x0cSearchNumber\x12\x1c.document_search.SearchQuery\x1a .document_search.SearchNumResult\"\x00\x62\x06proto3'
)




_SEARCHCONTENTRESULT = _descriptor.Descriptor(
  name='SearchContentResult',
  full_name='document_search.SearchContentResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='document_search.SearchContentResult.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=80,
)


_SEARCHNUMRESULT = _descriptor.Descriptor(
  name='SearchNumResult',
  full_name='document_search.SearchNumResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='document_search.SearchNumResult.status', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='document_search.SearchNumResult.msg', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=128,
)


_SEARCHQUERY = _descriptor.Descriptor(
  name='SearchQuery',
  full_name='document_search.SearchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='document_search.SearchQuery.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='document_search.SearchQuery.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['SearchContentResult'] = _SEARCHCONTENTRESULT
DESCRIPTOR.message_types_by_name['SearchNumResult'] = _SEARCHNUMRESULT
DESCRIPTOR.message_types_by_name['SearchQuery'] = _SEARCHQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchContentResult = _reflection.GeneratedProtocolMessageType('SearchContentResult', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHCONTENTRESULT,
  '__module__' : 'document_search_pb2'
  # @@protoc_insertion_point(class_scope:document_search.SearchContentResult)
  })
_sym_db.RegisterMessage(SearchContentResult)

SearchNumResult = _reflection.GeneratedProtocolMessageType('SearchNumResult', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHNUMRESULT,
  '__module__' : 'document_search_pb2'
  # @@protoc_insertion_point(class_scope:document_search.SearchNumResult)
  })
_sym_db.RegisterMessage(SearchNumResult)

SearchQuery = _reflection.GeneratedProtocolMessageType('SearchQuery', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHQUERY,
  '__module__' : 'document_search_pb2'
  # @@protoc_insertion_point(class_scope:document_search.SearchQuery)
  })
_sym_db.RegisterMessage(SearchQuery)



_DOCUMENTSEARCHSERVICE = _descriptor.ServiceDescriptor(
  name='DocumentSearchService',
  full_name='document_search.DocumentSearchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=175,
  serialized_end=368,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchContents',
    full_name='document_search.DocumentSearchService.SearchContents',
    index=0,
    containing_service=None,
    input_type=_SEARCHQUERY,
    output_type=_SEARCHCONTENTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchNumber',
    full_name='document_search.DocumentSearchService.SearchNumber',
    index=1,
    containing_service=None,
    input_type=_SEARCHQUERY,
    output_type=_SEARCHNUMRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOCUMENTSEARCHSERVICE)

DESCRIPTOR.services_by_name['DocumentSearchService'] = _DOCUMENTSEARCHSERVICE

# @@protoc_insertion_point(module_scope)
